### ISSUE TITLE
When will you publish this Action?

### ISSUE THREAD

**Issue by vybhav72954** [JasonEtco/slash-assign-action#1]

**Comment by afeld** [comment]
My workaround:

```yaml
steps:
  - name: Check out GitHub Action
    uses: actions/checkout@v2
    with:
      repository: JasonEtco/slash-assign-action
      ref: 842404647dfd10109c8c4feb3e776807eb5e2071
      path: .github/actions/slash-assign-action
  - name: Compile the Action
    run: |
      npm install
      npm run build
    working-directory: .github/actions/slash-assign-action

  - name: Assign the user or unassign stale assignments
    uses: ./.github/actions/slash-assign-action
```
